theme = "carbon"

[editor]
line-number = "relative"
cursorline = true # real√ßa a linha atual
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
inlay-hints-length-limit = 33

[editor.inline-diagnostics]
cursor-line = "hint"  # Mostra erros inline na linha do cursor principal. Use "warning" para incluir warnings, ou "hint" para todos.

[keys.insert]
C-space = "completion"
